# Generated by Django 2.2.5 on 2019-12-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('call', models.TextField()),
                ('status', models.PositiveSmallIntegerField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('output', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkerRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('status', models.PositiveSmallIntegerField()),
                ('curr', models.DateTimeField(auto_now=True)),
                ('total', models.PositiveIntegerField()),
            ],
        ),
    ]
