# Generated by Django 2.2.5 on 2019-12-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='pid',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
