# Generated by Django 2.2.5 on 2019-12-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_process_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerrecord',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='workerrecord',
            name='curr',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='workerrecord',
            name='total',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
