# Generated by Django 2.2.5 on 2020-01-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('process', '0004_auto_20191228_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='type',
            field=models.CharField(default='plot', max_length=16),
            preserve_default=False,
        ),
    ]
