# Generated by Django 2.2.5 on 2019-12-31 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Methods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('package', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('params', models.TextField()),
            ],
        ),
    ]
